name: manga_read
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  go_router: ^17.0.0
  sizer: ^2.0.15
  dartz: ^0.10.1

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_native_splash:
  color: "#121212"

  image: web/icons/Icon-512.png

  android_12:
    image: web/icons/Icon-192.png
    color: "#121212"

  android: true
  ios: true
  web: false
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21